### ISSUE TITLE
Error related to @types/react

### ISSUE THREAD

**Issue by venkata-ramana-subramanyam** [kathari00/keycloakify-starter-angular#1]
@kathari00  when i installed the keycloakify v10.0.0-rc.105 in my ng project and when i tried ng build, i was getting the below error message

![Pasted Graphic 17](https://github.com/kathari00/keycloakify-starter-angular/assets/97159195/e18199cc-0c8e-4f04-b352-79f343e9aae2)

By adding @types/react pkg, i was able to fix it.

I did not find the @types/react pkg in your project. May i know if you ever faced that error at all? Or did you do anything different?

Thanks

**Comment by kathari00** [comment]
Hi, I just updated the project. It is still very early in development. You can do ng serve for local development. You need to define a specific page in environment.ts. 
The command npx keycloakify start-keycloak should be working as well. Please let me know if it works for you. I will update the readme soon.
