### ISSUE TITLE
Include missing assets in repository

### ISSUE THREAD

**Issue by XERGER** [kathari00/keycloakify-starter-angular#2]
Hi Kathari,

would like to use this theme project in a Docker container so willing to help out as well, have some experience with angular.

currently the ng serve will fail for everyone that just pulls and uses ng serve i guess because there are missing assets that could also be included in the repository or added to an "installation" process.

```

Error: Can't resolve 'src/keycloak-theme/assets/keycloak-resources/login/resources/css/login.css' in 'G:\demo_cmake\keycloak\keycloak-theme'

Error: Can't resolve 'src/keycloak-theme/assets/keycloak-resources/login/resources/resources-common/lib/pficon/pficon.css' in 'G:\demo_cmake\keycloak\keycloak-theme'

Error: Can't resolve 'src/keycloak-theme/assets/keycloak-resources/login/resources/resources-common/node_modules/@patternfly/patternfly/patternfly.min.css' in 'G:\demo_cmake\keycloak\keycloak-theme'

Error: Can't resolve 'src/keycloak-theme/assets/keycloak-resources/login/resources/resources-common/node_modules/patternfly/dist/css/patternfly-additions.min.css' in 'G:\demo_cmake\keycloak\keycloak-theme'

Error: Can't resolve 'src/keycloak-theme/assets/keycloak-resources/login/resources/resources-common/node_modules/patternfly/dist/css/patternfly.min.css' in 'G:\demo_cmake\keycloak\keycloak-theme'
```

https://github.com/kathari00/keycloakify-starter-angular/blob/2e6298ee3e798ca72f87c7ef9c6b6c2347dcf293/src/keycloak-theme/login/template.component.ts#L111

**Comment by XERGER** [comment]
you maybe using discord or skype `?

**Comment by kathari00** [comment]
Hi, I updated the readme. You need to use the keycloakify command to copy the keycloak resources to assets. 

I am available on Discord.

**Comment by XERGER** [comment]
Ah Thanks. yes works!

could you add me please on discord ? :)

name: iii3498
